{% set name = "multidict" %}
{% set version = "6.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/multidict/multidict-{{ version }}.tar.gz
  sha256: 22ae2ebf9b0c69d206c003e2f6a914ea33f0a932d4aa16f236afc049d9958f4a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<38]
  patches:
    # backport https://github.com/aio-libs/multidict/pull/864
    - patches/0001-Fix-usage-python-C-API-for-version-greater-3.9-and-f.patch

requirements:
  build:
    - {{ compiler('c') }}
    - patch # [unix]
    - m2-patch # [win]
  host:
    - cython 0.29
    - python
    - pip
    - setuptools >=40
    - wheel
    - typing-extensions >=4.1.0 # [py<311]
  run:
    - python

test:
  imports:
    - multidict
  source_files:
    - tests
  requires:
    - pytest
    - pip
    - typing-extensions >=4.1.0 # [py<311]
  commands:
    - pip check
    - py.test tests

about:
  home: https://github.com/aio-libs/multidict
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: The multidict implementation
  description: |
    Multidicts are useful for working with HTTP headers, URL query args etc.
  doc_url: https://multidict.aio-libs.org/
  dev_url: https://github.com/aio-libs/multidict

extra:
  recipe-maintainers:
    - sodre
    - kszucs
