{% set name = "multidict" %}
{% set version = "3.3.2" %}
{% set sha256 = "f82e61c7408ed0dce1862100db55595481911f159d6ddec0b375d35b6449509b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: true  # [py2k]

requirements:
  build:
    - python
    - setuptools
    - toolchain
  run:
    - python

test:
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - py.test tests

about:
  home: http://github.com/aio-libs/multidict
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'multidict implementation'

  description: |
    Multidicts are useful for working with HTTP headers, URL query args etc.
  doc_url: http://multidict.readthedocs.io/
  dev_url: http://github.com/aio-libs/multidict
  doc_source_url: https://github.com/aio-libs/multidict/tree/master/docs

extra:
  recipe-maintainers:
    - sodre
    - kszucs
