{% set name = "multidict" %}
{% set version = "6.0.4" %}
{% set sha256 = "3666906492efb76453c0e7b97f2cf459b0682e7402c0489a95484965dbc1da49" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython 0.29
    - python
    - pip
    - setuptools >=40
    - wheel
  run:
    - python

test:
  import:
    - multidict
  source_files:
    - tests
  requires:
    - pytest
    - pip
  commands:
    - pip check
    - py.test tests

about:
  home: https://github.com/aio-libs/multidict
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: The multidict implementation
  description: |
    Multidicts are useful for working with HTTP headers, URL query args etc.
  doc_url: https://multidict.aio-libs.org/
  dev_url: https://github.com/aio-libs/multidict

extra:
  recipe-maintainers:
    - sodre
    - kszucs
