travis:
  secure:
    BINSTAR_TOKEN: bc9IrEDvqnuH+ZGGGvcPAFrr026iipTxiovuaIc4onrRpbQYuir04BOcy+OtncxNPzlR7gdZOVgEVHKaMORzeFbQWn9IF1/dJHPrC2gGabM+qc9ZrZ+ebw4s/L1gQrQAlSSdB7+q21HDyfRrYfWr5oXxlajqcBktadS90MnZXpb/ifCUa/zXdyQCM5hNVkDfvnGKYBTMjU5ZHvf2bN/9VWQWGBHvi+mh4nFjKSEk+Zs+kYx+5h8QUsYYgUkTcoK9lRT6FVf8tlsUAbd99QtIPhBJiZvVvddKC891LqinVVUdn2ZM3Yz7xKgzQeGVHosUPOGbM7xq+RmTWRVpxYhhnNh4i4lPginm7II0sAjkhHBqck+vF1Pb16RB+LAVLCTYc3JBdZlh0QB6F1g9lMVTwZJtBZec69d99RrRNVZTNLe/cibi1ZEXtZIt0vpoQBJOubVeLIY4RYWaspKvCZipuKtgn3IuwA9vVC2sX37Hj0xMpxVcdmbmPWP6rKTbL9U6nPEUnT1I4C/qIeMtRIj0/9iBPLpLvcW7xpU245bf303dE/9+ts0z/16Nw6UkS7vLw1nqH1d+/NVnWVWB17g6DyLKMyLxleFpx1n72fvIr8ZyaQ9WWhsB1nKT+inY1RrrkEZswk+0uR5ig4IpQrWO7yFclhIzp1HYP71zRfC60jc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
